version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    profiles:
      - dev
      - staging
      - production


  backend:
    build:
      context: ./flight-booking-backend
      dockerfile: Dockerfile
    container_name: flight_booking_backend
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: db
      PORT: ${PORT}
    depends_on:
      - db
    ports:
      - "3000:3000"
    profiles:
      - dev
      - staging
      - production


  frontend:
    build:
      context: ./flight-booking-frontend
      dockerfile: Dockerfile
    container_name: flight_booking_frontend
    restart: always
    ports:
      - "3001:3000"  
    environment:
      REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
    profiles:
      - dev
      - staging
      - production

volumes:
  postgres_data:
    driver: local
