name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
      - stage
  pull_request:
    branches:
      - main
      - dev
      - stage

jobs:
  ci:
    name: CI Workflow
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js for Backend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install Backend Dependencies and Run Tests
      - name: Install Backend Dependencies
        working-directory: ./flight-booking-backend
        run: |
          npm install
        #   npm test

      # Step 4: Set up Node.js for Frontend
      - name: Install Frontend Dependencies
        working-directory: ./flight-booking-frontend
        run: |
          npm install
        #   npm test

      # Step 5: Build and Test Docker Compose
      - name: Test Docker Compose Build
        run: |
          docker compose -f docker-compose.yml --profile dev up --build --detach
          docker ps
          docker compose down
