name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
      - stage
  pull_request:
    branches:
      - main
      - dev
      - stage

jobs:
  ci:
    name: CI Workflow
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js for Backend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Set Environment Variables from Secrets
      - name: Set environment variables
        run: |
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> $GITHUB_ENV
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "PORT=${{ secrets.PORT }}" >> $GITHUB_ENV
          echo "REACT_APP_BASE_URL=${{ secrets.REACT_APP_BASE_URL }}" >> $GITHUB_ENV

      # Step 4: Install Backend Dependencies and Run Tests
      - name: Install Backend Dependencies
        working-directory: ./flight-booking-backend
        run: |
          npm install

      - name: Run Backend Tests
        working-directory: ./flight-booking-backend
        run: npm test

      # Step 5: Install Frontend Dependencies
      - name: Install Frontend Dependencies
        working-directory: ./flight-booking-frontend
        run: |
          npm install

      # Step 6: Start Docker Compose
      - name: Start Docker Compose
        run: |
          docker compose -f docker-compose.yml --profile dev up --build --detach
          docker ps

      # Step 7: Wait for the server to be ready
      - name: Wait for server to start
        run: |
          while ! curl --silent --head --fail http://localhost:3001; do
            echo "Waiting for server to start..."
            sleep 5
          done

      # Step 8: Run Frontend Tests (Cypress)
      - name: Run Frontend Tests
        working-directory: ./flight-booking-frontend
        run: npx cypress run

      # Step 9: Shut down Docker Compose after tests
      - name: Shutdown Docker Compose
        run: docker compose down
